const cartType = {
    TOGGLE_CART_HIDEEN : 'TOGGLE_CART_HIDEEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_GROUP_ITEM: 'CLEAR_GROUP_ITEM',
    CLEAR_CART_START: 'CLEAR_CART_START',
    CLEAR_CART_SUCCESS: 'CLEAR_CART_SUCCESS'
};

export default cartType;